apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: grup13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kube0.lacetania.cat/grup13/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "/api/"  # 🔁 Canviat a ruta relativa
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
      imagePullSecrets:
      - name: harbor-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: grup13
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
