apiVersion: v1
data:
  gestor_horaris.sql: "-- MySQL dump 10.13  Distrib 8.0.42, for Linux (x86_64)\n--\n--
    Host: localhost    Database: gestor_horaris\n-- ------------------------------------------------------\n--
    Server version\t8.0.42-0ubuntu0.22.04.1\n\n/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT
    */;\n/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n/*!40101
    SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n/*!50503 SET NAMES utf8mb4
    */;\n/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;\n/*!40103 SET TIME_ZONE='+00:00'
    */;\n/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;\n/*!40014
    SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;\n/*!40101
    SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n/*!40111 SET
    @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;\n\n--\n-- Table structure for table
    `entrades_sortides`\n--\n\nDROP TABLE IF EXISTS `entrades_sortides`;\n/*!40101
    SET @saved_cs_client     = @@character_set_client */;\n/*!50503 SET character_set_client
    = utf8mb4 */;\nCREATE TABLE `entrades_sortides` (\n  `id` int NOT NULL AUTO_INCREMENT,\n
    \ `usuari_id` int DEFAULT NULL,\n  `data` date NOT NULL,\n  `hora_entrada` timestamp
    NULL DEFAULT NULL,\n  `hora_sortida` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY
    (`id`),\n  KEY `usuari_id` (`usuari_id`),\n  CONSTRAINT `entrades_sortides_ibfk_1`
    FOREIGN KEY (`usuari_id`) REFERENCES `usuaris` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=54
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client
    = @saved_cs_client */;\n\n--\n-- Dumping data for table `entrades_sortides`\n--\n\nLOCK
    TABLES `entrades_sortides` WRITE;\n/*!40000 ALTER TABLE `entrades_sortides` DISABLE
    KEYS */;\nINSERT INTO `entrades_sortides` VALUES (1,3,'2025-03-12','2025-03-12
    17:46:02',NULL),(2,3,'2025-03-12',NULL,'2025-03-12 17:46:20'),(3,6,'2025-03-24','2025-03-24
    15:23:23',NULL),(4,6,'2025-03-24',NULL,'2025-03-24 15:24:46'),(5,6,'2025-03-27','2025-03-27
    14:41:11',NULL),(6,6,'2025-03-27',NULL,'2025-03-27 14:41:40'),(7,3,'2025-03-31','2025-03-31
    13:46:51',NULL),(8,3,'2025-03-31',NULL,'2025-03-31 13:53:08'),(9,3,'2025-04-03','2025-04-03
    15:38:23',NULL),(10,3,'2025-04-03',NULL,'2025-04-03 15:39:31'),(11,3,'2025-04-04','2025-04-04
    14:22:57',NULL),(12,3,'2025-04-04',NULL,'2025-04-04 14:24:17'),(13,3,'2025-04-08','2025-04-08
    18:20:25',NULL),(14,3,'2025-04-08',NULL,'2025-04-08 18:21:17'),(15,3,'2025-04-08','2025-04-08
    18:21:19',NULL),(16,3,'2025-04-08',NULL,'2025-04-08 18:22:01'),(17,3,'2025-04-08','2025-04-08
    18:24:17',NULL),(18,3,'2025-04-08',NULL,'2025-04-08 18:26:28'),(19,3,'2025-04-08','2025-04-08
    18:26:47',NULL),(20,3,'2025-04-08',NULL,'2025-04-08 18:26:53'),(21,3,'2025-04-08','2025-04-08
    18:27:30',NULL),(22,3,'2025-04-08',NULL,'2025-04-08 18:27:59'),(23,3,'2025-04-08','2025-04-08
    18:28:41',NULL),(24,3,'2025-04-08',NULL,'2025-04-08 18:29:06'),(50,3,'2025-04-21','2025-04-21
    18:20:34',NULL),(51,3,'2025-04-21',NULL,'2025-04-21 18:20:42'),(52,6,'2025-04-24','2025-04-24
    14:04:38',NULL),(53,6,'2025-04-24',NULL,'2025-04-24 14:05:21');\n/*!40000 ALTER
    TABLE `entrades_sortides` ENABLE KEYS */;\nUNLOCK TABLES;\n\n--\n-- Table structure
    for table `festius`\n--\n\nDROP TABLE IF EXISTS `festius`;\n/*!40101 SET @saved_cs_client
    \    = @@character_set_client */;\n/*!50503 SET character_set_client = utf8mb4
    */;\nCREATE TABLE `festius` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `data` date
    NOT NULL,\n  `nom` varchar(255) NOT NULL,\n  `created_at` timestamp NULL DEFAULT
    CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client = @saved_cs_client
    */;\n\n--\n-- Dumping data for table `festius`\n--\n\nLOCK TABLES `festius` WRITE;\n/*!40000
    ALTER TABLE `festius` DISABLE KEYS */;\n/*!40000 ALTER TABLE `festius` ENABLE
    KEYS */;\nUNLOCK TABLES;\n\n--\n-- Table structure for table `horari_dies`\n--\n\nDROP
    TABLE IF EXISTS `horari_dies`;\n/*!40101 SET @saved_cs_client     = @@character_set_client
    */;\n/*!50503 SET character_set_client = utf8mb4 */;\nCREATE TABLE `horari_dies`
    (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `horari_id` int NOT NULL,\n  `dia` date
    NOT NULL,\n  `hora_inici` time NOT NULL,\n  `hora_fi` time NOT NULL,\n  PRIMARY
    KEY (`id`),\n  UNIQUE KEY `horari_id` (`horari_id`,`dia`),\n  CONSTRAINT `horari_dies_ibfk_1`
    FOREIGN KEY (`horari_id`) REFERENCES `horaris` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=2
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client
    = @saved_cs_client */;\n\n--\n-- Dumping data for table `horari_dies`\n--\n\nLOCK
    TABLES `horari_dies` WRITE;\n/*!40000 ALTER TABLE `horari_dies` DISABLE KEYS */;\n/*!40000
    ALTER TABLE `horari_dies` ENABLE KEYS */;\nUNLOCK TABLES;\n\n--\n-- Table structure
    for table `horaris`\n--\n\nDROP TABLE IF EXISTS `horaris`;\n/*!40101 SET @saved_cs_client
    \    = @@character_set_client */;\n/*!50503 SET character_set_client = utf8mb4
    */;\nCREATE TABLE `horaris` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `usuari_id`
    int DEFAULT NULL,\n  `data_inici` date NOT NULL,\n  `data_fi` date NOT NULL,\n
    \ PRIMARY KEY (`id`),\n  KEY `usuari_id` (`usuari_id`),\n  CONSTRAINT `horaris_ibfk_1`
    FOREIGN KEY (`usuari_id`) REFERENCES `usuaris` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=7
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client
    = @saved_cs_client */;\n\n--\n-- Dumping data for table `horaris`\n--\n\nLOCK
    TABLES `horaris` WRITE;\n/*!40000 ALTER TABLE `horaris` DISABLE KEYS */;\n/*!40000
    ALTER TABLE `horaris` ENABLE KEYS */;\nUNLOCK TABLES;\n\n--\n-- Table structure
    for table `logs`\n--\n\nDROP TABLE IF EXISTS `logs`;\n/*!40101 SET @saved_cs_client
    \    = @@character_set_client */;\n/*!50503 SET character_set_client = utf8mb4
    */;\nCREATE TABLE `logs` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `usuari_id`
    int NOT NULL,\n  `accio` varchar(255) NOT NULL,\n  `descripcio` text,\n  `data_accio`
    timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `usuari_id`
    (`usuari_id`),\n  CONSTRAINT `logs_ibfk_1` FOREIGN KEY (`usuari_id`) REFERENCES
    `usuaris` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client = @saved_cs_client
    */;\n\n--\n-- Dumping data for table `logs`\n--\n\nLOCK TABLES `logs` WRITE;\n/*!40000
    ALTER TABLE `logs` DISABLE KEYS */;\nINSERT INTO `logs` VALUES (1,6,'Sol·licitud
    de vacances','Sol·licitud creada per usuari 6 del 2025-03-29 al 2025-03-30','2025-03-27
    18:12:05');\n/*!40000 ALTER TABLE `logs` ENABLE KEYS */;\nUNLOCK TABLES;\n\n--\n--
    Table structure for table `reports`\n--\n\nDROP TABLE IF EXISTS `reports`;\n/*!40101
    SET @saved_cs_client     = @@character_set_client */;\n/*!50503 SET character_set_client
    = utf8mb4 */;\nCREATE TABLE `reports` (\n  `id` int NOT NULL AUTO_INCREMENT,\n
    \ `usuari_id` int DEFAULT NULL,\n  `data_generacio` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n
    \ `format` enum('PDF','Excel') NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `usuari_id`
    (`usuari_id`),\n  CONSTRAINT `reports_ibfk_1` FOREIGN KEY (`usuari_id`) REFERENCES
    `usuaris` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101
    SET character_set_client = @saved_cs_client */;\n\n--\n-- Dumping data for table
    `reports`\n--\n\nLOCK TABLES `reports` WRITE;\n/*!40000 ALTER TABLE `reports`
    DISABLE KEYS */;\nINSERT INTO `reports` VALUES (1,3,'2025-03-12 17:47:01','PDF'),(2,3,'2025-03-13
    16:23:40','PDF');\n/*!40000 ALTER TABLE `reports` ENABLE KEYS */;\nUNLOCK TABLES;\n\n--\n--
    Table structure for table `rols`\n--\n\nDROP TABLE IF EXISTS `rols`;\n/*!40101
    SET @saved_cs_client     = @@character_set_client */;\n/*!50503 SET character_set_client
    = utf8mb4 */;\nCREATE TABLE `rols` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `nom`
    varchar(50) NOT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=3
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client
    = @saved_cs_client */;\n\n--\n-- Dumping data for table `rols`\n--\n\nLOCK TABLES
    `rols` WRITE;\n/*!40000 ALTER TABLE `rols` DISABLE KEYS */;\nINSERT INTO `rols`
    VALUES (1,'Administrador'),(2,'Treballador');\n/*!40000 ALTER TABLE `rols` ENABLE
    KEYS */;\nUNLOCK TABLES;\n\n--\n-- Table structure for table `tasques`\n--\n\nDROP
    TABLE IF EXISTS `tasques`;\n/*!40101 SET @saved_cs_client     = @@character_set_client
    */;\n/*!50503 SET character_set_client = utf8mb4 */;\nCREATE TABLE `tasques` (\n
    \ `id` int NOT NULL AUTO_INCREMENT,\n  `usuari_id` int NOT NULL,\n  `data` date
    NOT NULL,\n  `descripcio` text NOT NULL,\n  `created_at` timestamp NULL DEFAULT
    CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON
    UPDATE CURRENT_TIMESTAMP,\n  `completada` tinyint(1) DEFAULT '0',\n  `hora_inici`
    time DEFAULT NULL,\n  `hora_fi` time DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY
    `usuari_id` (`usuari_id`),\n  CONSTRAINT `tasques_ibfk_1` FOREIGN KEY (`usuari_id`)
    REFERENCES `usuaris` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=35
    DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101 SET character_set_client
    = @saved_cs_client */;\n\n--\n-- Dumping data for table `tasques`\n--\n\nLOCK
    TABLES `tasques` WRITE;\n/*!40000 ALTER TABLE `tasques` DISABLE KEYS */;\nINSERT
    INTO `tasques` VALUES (33,3,'2025-04-25','Tasca de Node per fer.','2025-04-24
    15:30:54','2025-04-25 15:23:29',0,'11:30:00','13:30:00'),(34,3,'2025-04-10','Tasca
    Node','2025-04-24 15:31:28','2025-04-24 15:31:30',1,'13:31:00','15:31:00');\n/*!40000
    ALTER TABLE `tasques` ENABLE KEYS */;\nUNLOCK TABLES;\n\n--\n-- Table structure
    for table `usuaris`\n--\n\nDROP TABLE IF EXISTS `usuaris`;\n/*!40101 SET @saved_cs_client
    \    = @@character_set_client */;\n/*!50503 SET character_set_client = utf8mb4
    */;\nCREATE TABLE `usuaris` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `nom` varchar(100)
    NOT NULL,\n  `cognoms` varchar(255) NOT NULL,\n  `correu` varchar(100) NOT NULL,\n
    \ `contrasenya` varchar(255) NOT NULL,\n  `rol_id` int DEFAULT NULL,\n  PRIMARY
    KEY (`id`),\n  UNIQUE KEY `correu` (`correu`),\n  KEY `rol_id` (`rol_id`),\n  CONSTRAINT
    `usuaris_ibfk_1` FOREIGN KEY (`rol_id`) REFERENCES `rols` (`id`)\n) ENGINE=InnoDB
    AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101
    SET character_set_client = @saved_cs_client */;\n\n--\n-- Dumping data for table
    `usuaris`\n--\n\nLOCK TABLES `usuaris` WRITE;\n/*!40000 ALTER TABLE `usuaris`
    DISABLE KEYS */;\nINSERT INTO `usuaris` VALUES (1,'Joan','Llobet','joan@example.com','$2b$10$PIDOS4v4FkJtalyPrKV3qO6Su.1C0qYcT3czoTT3YrykiTVySVufq',2),(3,'Admin','Secret','admin@example.com','$2b$10$Ws1r4FVh1BEIXSHaqGkWM.4Ju6BIneOLEFZKFYR8gOF5ZuEBCttsq',1),(4,'prova','','prova@gmail.com','$2b$10$uEKYgWGGuquYRtlwOHxTqO9SFgl.hF5wIYIF5CHmpui08tGMTjLPS',2),(6,'Treballador
    1','','treballador1@gmail.com','$2b$10$o7bx4Um1DkRl0Z.ZHdlIEey9CeVywzUmlnOSxfWKe.QIPv2qWYBim',2),(7,'Treballador
    2','','treballador2@gmail.com','$2b$10$1zZe54D9vuc483YU8KorxuFNhjpPA9VlccCRnc1n/6ApsbcmF4YKi',2),(8,'Bachir','Mejor','bachir@gmail.com','$2b$10$9Vhe1cOqSGcJNmh3cnKNh.mtGcRGXxYG1KjlDbLlZU8jSf0wvMTJm',2);\n/*!40000
    ALTER TABLE `usuaris` ENABLE KEYS */;\nUNLOCK TABLES;\n\n--\n-- Table structure
    for table `vacances`\n--\n\nDROP TABLE IF EXISTS `vacances`;\n/*!40101 SET @saved_cs_client
    \    = @@character_set_client */;\n/*!50503 SET character_set_client = utf8mb4
    */;\nCREATE TABLE `vacances` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `usuari_id`
    int NOT NULL,\n  `data_inici` date NOT NULL,\n  `data_fi` date NOT NULL,\n  `estat`
    enum('pendent','aprovat','rebutjat') DEFAULT 'pendent',\n  `created_at` timestamp
    NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,\n  `notificat` tinyint(1) DEFAULT '0',\n  PRIMARY
    KEY (`id`),\n  KEY `usuari_id` (`usuari_id`),\n  CONSTRAINT `vacances_ibfk_1`
    FOREIGN KEY (`usuari_id`) REFERENCES `usuaris` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB
    AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;\n/*!40101
    SET character_set_client = @saved_cs_client */;\n\n--\n-- Dumping data for table
    `vacances`\n--\n\nLOCK TABLES `vacances` WRITE;\n/*!40000 ALTER TABLE `vacances`
    DISABLE KEYS */;\nINSERT INTO `vacances` VALUES (1,6,'2025-03-29','2025-03-30','pendent','2025-03-27
    18:12:05','2025-03-27 18:12:05',0);\n/*!40000 ALTER TABLE `vacances` ENABLE KEYS
    */;\nUNLOCK TABLES;\n/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;\n\n/*!40101 SET
    SQL_MODE=@OLD_SQL_MODE */;\n/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS
    */;\n/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;\n/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT
    */;\n/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n/*!40101
    SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;\n/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES
    */;\n\n-- Dump completed on 2025-05-09 15:52:58\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-init
  namespace: grup13
